### ISSUE TITLE
any hint on how to get this up and running?

### ISSUE THREAD

**Issue by mkschulze** [jordansinger/health-macos-swiftui-example#1]
I read that blog here: https://9to5mac.com/2020/07/14/apple-health-app-mac-swiftui-concept/

But am a bit confused as there is not a single hint on how to run this or build this. I have no experience with SwiftUI. A few words for how to install would help in the read.me I think. thx

**Comment by miallo** [comment]
You can't use this, since it is only a concept. I also stumbled across this in the same article.

If you look [here](https://github.com/jordansinger/health-macos-swiftui-example/blob/master/Health/ContentView.swift#L48-L54) you will see that the values from the image in the README are hardcoded in the code. This program does not use real data.

If you wanted to run it nevertheless, you would need to download Xcode from the App Store (Apples software development program) and you would need a developer account (which nowadays I think does *not* require you to pay 100$ per year anymore, but still...).

**Comment by mkschulze** [comment]
thx for letting me know. Strange that there isn't a native way to viz that data. I got an export app of the health data now, but it's a bit old fashioned.
